### ISSUE TITLE
KeyError when running the default code

### ISSUE THREAD

**Issue by ashok-arora** [SOTIF-AVLab/SinD#8]
Hey, I ran the default code given in the repository but it returned the following error:
```bash
Traceback (most recent call last):
  File "/home/ashok/Desktop/SinD/SIND-Vis-tool/VisMain.py", line 37, in <module>
    visualization_plot = Visualizer(config)
  File "/home/ashok/Desktop/SinD/SIND-Vis-tool/intersection_visualizer.py", line 32, in __init__
    self.__interface_init()
  File "/home/ashok/Desktop/SinD/SIND-Vis-tool/intersection_visualizer.py", line 141, in __interface_init
    self.update_figure()
  File "/home/ashok/Desktop/SinD/SIND-Vis-tool/intersection_visualizer.py", line 457, in update_figure
    value = self.VehTracks[track_id]
KeyError: 4
```
What can I do to resolve the error?

**Comment by ashok-arora** [comment]
Hey, after a bit of modifying the code as follows, it worked:

```bash
diff --git a/SIND-Vis-tool/intersection_visualizer.py b/SIND-Vis-tool/intersection_visualizer.py
index b8faff1..ce64f83 100644
--- a/SIND-Vis-tool/intersection_visualizer.py
+++ b/SIND-Vis-tool/intersection_visualizer.py
@@ -454,7 +454,7 @@ class Visualizer(object):
         for track_id in self.ids_for_frame[self.current_frame]["veh"]:
             # object is visible
             frame_id = self.current_frame - self.veh_tracks_meta[track_id]['initialFrame']
-            value = self.VehTracks[track_id]
+            value = self.VehTracks[(track_id, )]
             bbox = value['bbox'][frame_id, :, :]
             tri = value['triangle'][frame_id, :, :]
             if track_id not in self.plot_objs['veh']:
@@ -533,7 +533,7 @@ class Visualizer(object):
         for track_id in self.ids_for_frame[self.current_frame]["ped"]:
 
             frame_id = self.current_frame - self.ped_tracks_meta[track_id]['initialFrame']
-            value = self.PedTracks[track_id]
+            value = self.PedTracks[(track_id, )]
             bbox = value['bbox'][frame_id, :, :]
             if track_id not in self.plot_objs['ped']:
                 color = self.colors[value["agent_type"]]
```

**Comment by TheDarkKnight1998** [comment]
> 嘿嘿，按照如下方式修改代码后，它就工作了：
> 
> ```shell
> diff --git a/SIND-Vis-tool/intersection_visualizer.py b/SIND-Vis-tool/intersection_visualizer.py
> index b8faff1..ce64f83 100644
> --- a/SIND-Vis-tool/intersection_visualizer.py
> +++ b/SIND-Vis-tool/intersection_visualizer.py
> @@ -454,7 +454,7 @@ class Visualizer(object):
>          for track_id in self.ids_for_frame[self.current_frame]["veh"]:
>              # object is visible
>              frame_id = self.current_frame - self.veh_tracks_meta[track_id]['initialFrame']
> -            value = self.VehTracks[track_id]
> +            value = self.VehTracks[(track_id, )]
>              bbox = value['bbox'][frame_id, :, :]
>              tri = value['triangle'][frame_id, :, :]
>              if track_id not in self.plot_objs['veh']:
> @@ -533,7 +533,7 @@ class Visualizer(object):
>          for track_id in self.ids_for_frame[self.current_frame]["ped"]:
>  
>              frame_id = self.current_frame - self.ped_tracks_meta[track_id]['initialFrame']
> -            value = self.PedTracks[track_id]
> +            value = self.PedTracks[(track_id, )]
>              bbox = value['bbox'][frame_id, :, :]
>              if track_id not in self.plot_objs['ped']:
>                  color = self.colors[value["agent_type"]]
> ```

Thank you for pointing out the mistake correctly,  and sorry for slow response, this error result by pandas version inconsistent with our past used, factually  , such the use in our code  may requires pandas version < 2.0.0.
